"""baseline: 9 GMS tables

Revision ID: 58a1580c9237
Revises: 
Create Date: 2026-07-08 02:14:34.621941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '58a1580c9237'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('booking_events', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
    op.drop_index(op.f('idx_booking'), table_name='booking_events')
    op.create_index(op.f('ix_booking_events_booking_id'), 'booking_events', ['booking_id'], unique=False)
    op.alter_column('bookings', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
    op.alter_column('bookings', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
    op.drop_index(op.f('idx_customer'), table_name='bookings')
    op.drop_index(op.f('idx_provider'), table_name='bookings')
    op.drop_index(op.f('idx_status'), table_name='bookings')
    op.create_index(op.f('ix_bookings_customer_id'), 'bookings', ['customer_id'], unique=False)
    op.create_index(op.f('ix_bookings_provider_id'), 'bookings', ['provider_id'], unique=False)
    op.create_index(op.f('ix_bookings_status'), 'bookings', ['status'], unique=False)
    op.alter_column('messages', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
    op.drop_index(op.f('idx_pair'), table_name='messages')
    op.drop_index(op.f('idx_receiver_unread'), table_name='messages')
    op.alter_column('notifications', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
    op.drop_index(op.f('idx_is_read'), table_name='notifications')
    op.drop_index(op.f('idx_user'), table_name='notifications')
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.alter_column('reviews', 'rating',
               existing_type=mysql.TINYINT(display_width=4),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('reviews', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
    op.drop_index(op.f('idx_provider'), table_name='reviews')
    op.create_index(op.f('ix_reviews_provider_id'), 'reviews', ['provider_id'], unique=False)
    op.alter_column('search_terms', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
    op.drop_index(op.f('idx_term'), table_name='search_terms')
    op.drop_index(op.f('term'), table_name='search_terms')
    op.create_index(op.f('ix_search_terms_term'), 'search_terms', ['term'], unique=True)
    op.alter_column('services', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
    op.alter_column('services', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
    op.drop_index(op.f('idx_category'), table_name='services')
    op.drop_index(op.f('idx_city'), table_name='services')
    op.drop_index(op.f('idx_provider'), table_name='services')
    op.create_index(op.f('ix_services_category_id'), 'services', ['category_id'], unique=False)
    op.create_index(op.f('ix_services_city'), 'services', ['city'], unique=False)
    op.create_index(op.f('ix_services_provider_id'), 'services', ['provider_id'], unique=False)
    op.alter_column('users', 'location_text',
               existing_type=mysql.VARCHAR(length=200),
               type_=sa.String(length=150),
               existing_nullable=False,
               existing_server_default=sa.text("''"))
    op.alter_column('users', 'country',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=80),
               existing_nullable=False,
               existing_server_default=sa.text("'India'"))
    op.alter_column('users', 'pincode',
               existing_type=mysql.VARCHAR(length=12),
               type_=sa.String(length=10),
               existing_nullable=False,
               existing_server_default=sa.text("''"))
    op.alter_column('users', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
    op.alter_column('users', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
    op.drop_index(op.f('idx_phone'), table_name='users')
    op.drop_index(op.f('idx_role'), table_name='users')
    op.drop_index(op.f('phone'), table_name='users')
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.create_index(op.f('phone'), 'users', ['phone'], unique=True)
    op.create_index(op.f('idx_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('idx_phone'), 'users', ['phone'], unique=False)
    op.alter_column('users', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
    op.alter_column('users', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
    op.alter_column('users', 'pincode',
               existing_type=sa.String(length=10),
               type_=mysql.VARCHAR(length=12),
               existing_nullable=False,
               existing_server_default=sa.text("''"))
    op.alter_column('users', 'country',
               existing_type=sa.String(length=80),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False,
               existing_server_default=sa.text("'India'"))
    op.alter_column('users', 'location_text',
               existing_type=sa.String(length=150),
               type_=mysql.VARCHAR(length=200),
               existing_nullable=False,
               existing_server_default=sa.text("''"))
    op.drop_index(op.f('ix_services_provider_id'), table_name='services')
    op.drop_index(op.f('ix_services_city'), table_name='services')
    op.drop_index(op.f('ix_services_category_id'), table_name='services')
    op.create_index(op.f('idx_provider'), 'services', ['provider_id'], unique=False)
    op.create_index(op.f('idx_city'), 'services', ['city'], unique=False)
    op.create_index(op.f('idx_category'), 'services', ['category_id'], unique=False)
    op.alter_column('services', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
    op.alter_column('services', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
    op.drop_index(op.f('ix_search_terms_term'), table_name='search_terms')
    op.create_index(op.f('term'), 'search_terms', ['term'], unique=True)
    op.create_index(op.f('idx_term'), 'search_terms', ['term'], unique=False)
    op.alter_column('search_terms', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
    op.drop_index(op.f('ix_reviews_provider_id'), table_name='reviews')
    op.create_index(op.f('idx_provider'), 'reviews', ['provider_id'], unique=False)
    op.alter_column('reviews', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
    op.alter_column('reviews', 'rating',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(display_width=4),
               existing_nullable=False)
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.create_index(op.f('idx_user'), 'notifications', ['user_id'], unique=False)
    op.create_index(op.f('idx_is_read'), 'notifications', ['is_read'], unique=False)
    op.alter_column('notifications', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
    op.create_index(op.f('idx_receiver_unread'), 'messages', ['receiver_id', 'is_read'], unique=False)
    op.create_index(op.f('idx_pair'), 'messages', ['sender_id', 'receiver_id', 'created_at'], unique=False)
    op.alter_column('messages', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
    op.drop_index(op.f('ix_bookings_status'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_provider_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_customer_id'), table_name='bookings')
    op.create_index(op.f('idx_status'), 'bookings', ['status'], unique=False)
    op.create_index(op.f('idx_provider'), 'bookings', ['provider_id'], unique=False)
    op.create_index(op.f('idx_customer'), 'bookings', ['customer_id'], unique=False)
    op.alter_column('bookings', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
    op.alter_column('bookings', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
    op.drop_index(op.f('ix_booking_events_booking_id'), table_name='booking_events')
    op.create_index(op.f('idx_booking'), 'booking_events', ['booking_id'], unique=False)
    op.alter_column('booking_events', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
    # ### end Alembic commands ###
